# Generated by Django 5.1.2 on 2024-10-23 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='img',
            field=models.ImageField(upload_to='img/Certificados'),
        ),
    ]
